//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class AppointmentConfirmation
    {
        protected global::System.Web.UI.WebControls.SqlDataSource dsAppointment;

        protected global::System.Web.UI.WebControls.Panel pnlOk;

        protected global::System.Web.UI.WebControls.FormView fvAppt;

        protected global::System.Web.UI.WebControls.HyperLink lnkScheduleAnother;
    }
}
