//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Cart
    {
        protected global::System.Web.UI.WebControls.Literal litCartMessage;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.HyperLink lnkShop;

        protected global::System.Web.UI.WebControls.Repeater rptCart;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCartFooter;

        protected global::System.Web.UI.WebControls.Literal litSubtotal;

        protected global::System.Web.UI.WebControls.HyperLink lnkCheckout;
    }
}
