//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Checkout
    {
        protected global::System.Web.UI.WebControls.Literal litCheckoutError;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Panel pnlCheckout;

        protected global::System.Web.UI.WebControls.Repeater rptOrder;

        protected global::System.Web.UI.WebControls.Literal litOrderSubtotal;

        protected global::System.Web.UI.WebControls.Label lblName;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.Label lblEmail;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.SqlDataSource dsLocations;

        protected global::System.Web.UI.WebControls.DropDownList ddlPickupLocation;

        protected global::System.Web.UI.WebControls.Literal litLocationCard;

        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
    }
}
