//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkShopProducts;

        protected global::System.Web.UI.WebControls.HyperLink lnkHeroSchedule;
    }
}
