//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class DeleteAccount
    {
        protected global::System.Web.UI.WebControls.Label litDeleteError;

        protected global::System.Web.UI.WebControls.Literal litEmail;

        protected global::System.Web.UI.WebControls.Label lblPwd;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Label lblEmailConfirm;

        protected global::System.Web.UI.WebControls.TextBox txtEmailConfirm;

        protected global::System.Web.UI.WebControls.CheckBox chkUnderstand;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
    }
}
