//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Details
    {
        protected global::System.Web.UI.WebControls.SqlDataSource dsProduct;

        protected global::System.Web.UI.WebControls.FormView fvProduct;
    }
}
