//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class LoginSuccess
    {
        protected global::System.Web.UI.WebControls.Literal litName;

        protected global::System.Web.UI.WebControls.HyperLink lnkProfile;

        protected global::System.Web.UI.WebControls.HyperLink lnkShop;
    }
}
