//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class OrderConfirmation
    {
        protected global::System.Web.UI.WebControls.Panel pnlOk;

        protected global::System.Web.UI.WebControls.Repeater rptLines;

        protected global::System.Web.UI.WebControls.Literal litPickup;

        protected global::System.Web.UI.WebControls.Literal litTotal;

        protected global::System.Web.UI.WebControls.HyperLink lnkContinue;

        protected global::System.Web.UI.WebControls.Panel pnlMissing;
    }
}
