//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.Label litProfileMessage;

        protected global::System.Web.UI.WebControls.Label litProfileError;

        protected global::System.Web.UI.WebControls.Label lblFirst;

        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;

        protected global::System.Web.UI.WebControls.Label lblLast;

        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;

        protected global::System.Web.UI.WebControls.Label lblEmail;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        protected global::System.Web.UI.WebControls.Label lblPhone;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.Label lblVehicle;

        protected global::System.Web.UI.WebControls.TextBox txtVehicleInfo;

        protected global::System.Web.UI.WebControls.Label lblCurrentPwd;

        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        protected global::System.Web.UI.WebControls.Label lblNewPwd;

        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        protected global::System.Web.UI.WebControls.Label lblNewPwd2;

        protected global::System.Web.UI.WebControls.TextBox txtNewPasswordConfirm;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.HyperLink lnkDelete;
    }
}
