//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class RegisterSuccess
    {
        protected global::System.Web.UI.WebControls.Literal litEmail;

        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;

        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
    }
}
