//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.Label litRegisterError;

        protected global::System.Web.UI.WebControls.ValidationSummary vsRegister;

        protected global::System.Web.UI.WebControls.Label lblFirst;

        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;

        protected global::System.Web.UI.WebControls.Label lblLast;

        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;

        protected global::System.Web.UI.WebControls.Label lblEmail;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        protected global::System.Web.UI.WebControls.Label lblPwd;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPwd;

        protected global::System.Web.UI.WebControls.Label lblPwd2;

        protected global::System.Web.UI.WebControls.TextBox txtPasswordConfirm;

        protected global::System.Web.UI.WebControls.CompareValidator cvPwd;

        protected global::System.Web.UI.WebControls.Label lblPhone;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.Label lblVehicle;

        protected global::System.Web.UI.WebControls.TextBox txtVehicleInfo;

        protected global::System.Web.UI.WebControls.Button btnRegister;

        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;
    }
}
