//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Schedule
    {
        protected global::System.Web.UI.WebControls.Literal litScheduleError;

        protected global::System.Web.UI.WebControls.RadioButtonList rblService;

        protected global::System.Web.UI.WebControls.SqlDataSource dsLocations;

        protected global::System.Web.UI.WebControls.Label lblName;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.Label lblEmail;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.Label lblPhone;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.Label lblVehicle;

        protected global::System.Web.UI.WebControls.TextBox txtVehicle;

        protected global::System.Web.UI.WebControls.Label lblLocation;

        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;

        protected global::System.Web.UI.WebControls.Label lblApptDate;

        protected global::System.Web.UI.WebControls.TextBox txtApptDate;

        protected global::System.Web.UI.WebControls.Button btnConfirmAppt;
    }
}
