//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class Shop
    {
        protected global::System.Web.UI.WebControls.SqlDataSource dsProductTypes;

        protected global::System.Web.UI.WebControls.SqlDataSource dsTireSizes;

        protected global::System.Web.UI.WebControls.SqlDataSource dsWheelSizes;

        protected global::System.Web.UI.WebControls.SqlDataSource dsProducts;

        protected global::System.Web.UI.WebControls.DropDownList ddlProductType;

        protected global::System.Web.UI.WebControls.DropDownList ddlTireSize;

        protected global::System.Web.UI.WebControls.DropDownList ddlWheelSize;

        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Repeater rptProducts;
    }
}
