//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SueTheChef
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm formMain;

        protected global::System.Web.UI.WebControls.HyperLink lnkLogo;

        protected global::System.Web.UI.WebControls.HyperLink lnkHome;

        protected global::System.Web.UI.WebControls.HyperLink lnkProducts;

        protected global::System.Web.UI.WebControls.HyperLink lnkSchedule;

        protected global::System.Web.UI.WebControls.HyperLink lnkCart;

        protected global::System.Web.UI.WebControls.Literal litSessionCustomer;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
